### ISSUE TITLE
HTTP success, error deprecated

### ISSUE THREAD

**Issue by axos88** [greencatsoft/scalajs-angular#100]
https://code.angularjs.org/1.5.9/docs/api/ng/service/$http

The $http legacy promise methods success and error have been deprecated. Use the standard then method instead. If $httpProvider.useLegacyPromiseExtensions is set to false then these methods will throw $http/legacy error.

**Comment by mackler** [comment]
I was just updating some of my code to accommodate this deprecation.  Looking at the [definition of `this()`](https://github.com/greencatsoft/scalajs-angular/blob/master/src/main/scala/com/greencatsoft/angularjs/core/Q.scala#L60) I see the type of the "success" function is `js.Function1[T, T]` where `T` is the type of the HTTP request entity.  But according to [this migration guide](https://docs.angularjs.org/guide/migration#migrate1.5to1.6-ng-services-$http) as well as my own experimentation, it seems that the success function, rather than being passed a value of type `T` is passed a value of type [`HttpResult`](https://github.com/greencatsoft/scalajs-angular/blob/master/src/main/scala/com/greencatsoft/angularjs/core/Http.scala#L256), which in turn has a member named `data`.

Am I confused or is the definition of `this()` incorrect?

**Comment by mysticfall** [comment]
Closing, as it's fixed with #101. (Thanks, @axos88!)

@mackler You are correct about the return type being `HttpResult`, and it's the reason why we have a separate `HttpPromise`, which is just an alias for `Promise[HttpPromise[T]]`.
