### ISSUE TITLE
Support "controller-as" syntax in templates

### ISSUE THREAD

**Issue by rparree** [greencatsoft/scalajs-angular#30]
EDIT

" How would i go around and use the "controller-as" approach. Is that in fact just using scalajs and not your library? How would i register that controller constructor function?"

tx.,

**Comment by mysticfall** [comment]
If I'm not mistaken, what can be achieved by using the '_controller as_' syntax is that you can reference the controller instance directly from a view template, which should be possible as it is, provided you have specified ```@JSExport``` on any mehods or fields you want to access.

Note that you can reference it even with the traditional syntax, by ```controller``` variable, as shown in the TodoMVC example application.

Maybe we should make overriding the ```initialize(scope: Scope)``` method optional, in order to keep the code clean when using the _`controller-as`_ syntax.

I'm not sure if I understood your question correctly. If I didn't, please let me know.

Thanks!

**Comment by 4lex1v** [comment]
Hello, i'm also interested in this question, cause i prefer controller-as syntax and in the application which i'd like to rewrite with ScalaJS and Angular, it's quite important. Anyway, i've tried to setup the simplest app with this controller:
```scala
@JSExport
object SimpleController extends Controller {
  @JSExport
  val helloMessage = "Hello World"
}
```

and html:

```html
<div data-ng-controller="ScaldoController as vm">
    <p>Hello from angular {{ vm.helloMessage }}</p>
</div>
```

but, this works:

```html
<div data-ng-controller="ScaldoController">
    <p>Hello from angular {{ controller.helloMessage }}</p>
</div>
```

After looking at [this](https://docs.angularjs.org/guide/concepts#controller) article, it seems that in `Controller as smth`, angular looks `smth` in scope, where it's `smth: new Controller`. It's my first day with ScalaJS and i'm not an expert in angular, but it makes some sense.

**Comment by 4lex1v** [comment]
Ok, the article was right, angular tries to resolve this `smth` path in scope, so if we apply this trick, it would work:

```scala
@JSExport
object SimpleController extends Controller {
  @JSExport
  val helloMessage = "Hello Another World"

  override def initialize(scope: ScopeType): Unit = {
    super.initialize(scope)
    scope.vm = SimpleController
  }

  trait ScopeType extends Scope {
    var vm: Controller = js.native
  }
}
```

```html
    <div data-ng-controller="SimpleController as vm">
        <p>Hello from angular {{ vm.helloMessage }}</p>
    </div>
```

Is it possible to automate this somehow?

**Comment by mysticfall** [comment]
Finally, I was able to spend some time investigating this issue today. Unfortunately, it seems that there's a limitation in the implementation which prevents us from accessing the controller instance with the _controller-as_ syntax.

(For those who might be curious about the details: Scala.js objects are different from pure Javascript functions, so you can't interchange one with the other, so if you reference the controller instance directly with the _controller-as_ syntax, it returns the proxy object which bridges them, not the real Scala.js instance.)

So, I made a compromise with which you can access your controller instance as '_[name].controller_', where _[name]_ is the name used in the _controller-as_ declaration.

For instance, when you declare '_TodoCtrl as todo_', you can call its method like '_todo.controller.checkAll()_', instead of '_todo.checkAll()_'.

I've considered using the approach @4lex1v has suggested, but I wasn't able to find an easy way to automate it.

For now, I'm closing this issue, so please reopen it if you find any problem with the changes or have a better way to support this feature.

Thanks!
