### ISSUE TITLE
Get headers from http.get 

### ISSUE THREAD

**Issue by Passarinho4** [greencatsoft/scalajs-angular#86]
Hi, 

I need to get header from $http.get response. Angular provide headers - Header getter function (as described here : https://docs.angularjs.org/api/ng/service/$http). Could you tell me how can I get headers? HttpResult supports all other fields, but doesn't support headers.. 

I prepare class as this:

`@js.native
trait HttpHeadersResponse extends HttpResult {
  val headers:js.Any = js.native
}`

but this:
`    http.get[HttpHeadersResponse](Config.apiUrl + "login", httpConfig)
      .foreach(response => println(response.headers))`

prints undefined.. 

I tried many things, but what is more strange, when I use HttpResult instead of HttpHeadersResponse all fields (like data, config, status) are also undefined. 

Thanks for any suggestions.

**Comment by mysticfall** [comment]
To access the raw result of `$http.get` invocation, you can register a callback using `$http.then` instead of relying on implicit conversion to `HttpPromise`, as it will extract only the payload of the response automatically.

As an alternative, it is possible to use `Promise.promise2future` to convert the result into a Scala `Future`, because it will return the raw result without any conversion, unlike its counterpart in `HttpPromise`.

I also added `headers` function to `HttpResult` trait, so you won't have to extend it to access the function.

Please let me know if you need further help. Thanks!
